name: Mirror to Organization Repo

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2


      - name: Mirror to Organization Repo
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          gh repo create $REPO_NAME --private
          git remote add moulishop origin https://github.com/MolinaAlexandre/$(basename $GITHUB_REPOSITORY)
          git push moulishop

