name: Mirror to Organization Repo

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Mirror to Organization Repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          ORG_REPO="git@github.com:skead/${REPO_NAME}.git"

          # Check if repo exists
          if curl -s -H "Authorization: token $GH_PAT" https://api.github.com/repos/skead/$REPO_NAME | grep -q "Not Found"; then
            echo "Repository does not exist, creating..."
            # Replace the payload below with your required repository settings
            curl -X POST -H "Authorization: token $GH_PAT" https://api.github.com/orgs/skead/repos -d "{\"name\":\"$REPO_NAME\", \"private\": false}"
          else
            echo "Repository exists, skipping creation..."
          fi

          # Mirror push to the organization repo
          git push --mirror $ORG_REPO
