name: Mirror to Organization Repo

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Mirror to Organization Repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          gh repo create $REPO_NAME --private
          git remote add moulishop origin https://github.com/MolinaAlexandre/$(basename $GITHUB_REPOSITORY)
          git push moulishop

